// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"agents/claude-code.mdx": () => import("../content/docs/agents/claude-code.mdx?collection=docs"), "agents/generic-openai.mdx": () => import("../content/docs/agents/generic-openai.mdx?collection=docs"), "agents/openclaw.mdx": () => import("../content/docs/agents/openclaw.mdx?collection=docs"), "agents/opencode.mdx": () => import("../content/docs/agents/opencode.mdx?collection=docs"), "api/anthropic.mdx": () => import("../content/docs/api/anthropic.mdx?collection=docs"), "api/errors.mdx": () => import("../content/docs/api/errors.mdx?collection=docs"), "api/openai.mdx": () => import("../content/docs/api/openai.mdx?collection=docs"), "api/overview.mdx": () => import("../content/docs/api/overview.mdx?collection=docs"), "api/xllmapi-unified.mdx": () => import("../content/docs/api/xllmapi-unified.mdx?collection=docs"), "community/faq.mdx": () => import("../content/docs/community/faq.mdx?collection=docs"), "community/feedback.mdx": () => import("../content/docs/community/feedback.mdx?collection=docs"), "community/groups.mdx": () => import("../content/docs/community/groups.mdx?collection=docs"), "getting-started/api-key.mdx": () => import("../content/docs/getting-started/api-key.mdx?collection=docs"), "getting-started/auth.mdx": () => import("../content/docs/getting-started/auth.mdx?collection=docs"), "getting-started/first-call.mdx": () => import("../content/docs/getting-started/first-call.mdx?collection=docs"), "getting-started/introduction.mdx": () => import("../content/docs/getting-started/introduction.mdx?collection=docs"), "model-network/connect-model.mdx": () => import("../content/docs/model-network/connect-model.mdx?collection=docs"), "model-network/distributed-node.mdx": () => import("../content/docs/model-network/distributed-node.mdx?collection=docs"), "model-network/economy.mdx": () => import("../content/docs/model-network/economy.mdx?collection=docs"), "model-network/models.mdx": () => import("../content/docs/model-network/models.mdx?collection=docs"), "model-network/overview.mdx": () => import("../content/docs/model-network/overview.mdx?collection=docs"), "model-network/platform-node.mdx": () => import("../content/docs/model-network/platform-node.mdx?collection=docs"), }),
};
export default browserCollections;